dist: trusty
language: python
python:
  - "3.6"
services: postgresql
before_install:
  - python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
install:
  - pip install -r requirements/base.txt
  - pip install coveralls
  - npm install -g bower
before_script:
  - psql -c "create database gambit;" -U postgres
  - psql -c "CREATE USER gambit WITH PASSWORD 'gambit';" -U postgres
  - psql -c "ALTER USER gambit CREATEDB;" -U postgres
script:
  - cp gambit/config.example.yaml gambit/config.yaml
  - export DJANGO_SETTINGS_MODULE="gambit.settings.development"
  - python manage.py migrate
  - python manage.py makemigrations gambit
  - python manage.py migrate
  - bower install --save --production misc/bower.json
  - python manage.py collectstatic --noinput --clear --verbosity 0
  - coverage run --source='.' manage.py test gambit
after_success:
  - coveralls
