os: linux
dist: trusty
language: python
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
python:
  - "3.6"
services: postgresql
before_install:
  # Disable non-blocking IO
  # https://github.com/travis-ci/travis-ci/issues/4704
  - python -c 'import os,sys; os.set_blocking(sys.stdout.fileno(), True)'
install:
  - pip install coveralls -r requirements/base.txt
  - npm install -g bower less@2.7.2 less-plugin-clean-css
before_script:
  - psql -c "create database gambit;" -U postgres
  - psql -c "CREATE USER username WITH PASSWORD 'password';" -U postgres
  - psql -c "ALTER USER username CREATEDB;" -U postgres
  - psql -c "CREATE EXTENSION IF NOT EXISTS hstore;" -U postgres
  - chmod +x build/build.sh
  - cp gambit/config.example.yaml gambit/config.yaml
script: bash build/build.sh -s development
after_success:
  - coveralls
notifications:
  slack:
    secure: fRaJc3F2C6cA6/ITnYO5b4MrzamcEoJZjnn1A3NLTvEOfO6MoBOQz2460/jct1iHD2k+eD087bWIfSYJ3SLvloNbLyhelOhAqoTL3JrB2oZvx8AXE+8bp8aEd6HRyI/rfQ0JufyPDh0w1/OeU1qus8NGZIw5uPm7gO4GaOkN4s24NdIFk+Q1Y4vPQWS0Ev/bh+bwCpwmvF9jxiw+QCV3g9d2IDbPnA6sxZ7o9Ilx1tUlQOjuGnkSKTv48VaOsctHQt3UTJEGPKcHilip3CM+ngPlzmPImR2ObchErhiPOfKhrtuR02+im+ozZ5wCtY7WCD893leoeu1ownKbUEEYhAwUXyeeYqNOKpXVHH9XRNNTMOafTCl27UFhgz0curcaWuk84fl6jOsnY0KW07No4uUyp4z3zfW14/iv5D1gvUeNN7wcXZKeUaGuo0pUWTo6zPwbgaGPHe5NKNeFwhH0UL3nduaLlBsS/DYlzhgnnLqVPFE1h6yL79tO1YAVTyhNnkfw7HPwrPgaOmzeUGiN54Sbw2EALHWTmpVzHXP3zxB6omd+GAt2Pf+Kk9Ol63eZSCf1AoIKr0GU/d5f51e3Ozo8KIg2HS3N67R9wcUZI/0jZM5cb89+W1lYg1UdcWZQfsUxJzQgPFWq1SzPdN56ethKTJWghb29ygMc1VrEm5c=
    on_success: always
    on_failure: always
    on_pull_requests: true
