dist: trusty
language: python
python:
  - "3.6"
services: postgresql
before_install:
  - python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
install:
  - pip install coveralls -r requirements/base.txt
  - npm install -g bower less@2.7.2 less-plugin-clean-css
before_script:
  - psql -c "create database gambit;" -U postgres
  - psql -c "CREATE USER gambit WITH PASSWORD 'gambit';" -U postgres
  - psql -c "ALTER USER gambit CREATEDB;" -U postgres
script:
  - cp gambit/config.example.yaml gambit/config.yaml
  - export DJANGO_SETTINGS_MODULE="gambit.settings.development"
  - python manage.py migrate
  - python manage.py makemigrations gambit
  - python manage.py migrate
  - bower install --save --production ./misc/bower.json
  - lessc --source-map-less-inline --source-map-map-inline --clean-css bower_components/flat-ui/less/flat-ui.less bower_components/flat-ui/dist/css/flat-ui-44con.min.css
  - python manage.py collectstatic --noinput --clear --verbosity 0
  - python manage.py compress --force --verbosity 0
  - coverage run --source='.' manage.py test gambit
after_success:
  - coveralls
notifications:
  slack:
    secure: fRaJc3F2C6cA6/ITnYO5b4MrzamcEoJZjnn1A3NLTvEOfO6MoBOQz2460/jct1iHD2k+eD087bWIfSYJ3SLvloNbLyhelOhAqoTL3JrB2oZvx8AXE+8bp8aEd6HRyI/rfQ0JufyPDh0w1/OeU1qus8NGZIw5uPm7gO4GaOkN4s24NdIFk+Q1Y4vPQWS0Ev/bh+bwCpwmvF9jxiw+QCV3g9d2IDbPnA6sxZ7o9Ilx1tUlQOjuGnkSKTv48VaOsctHQt3UTJEGPKcHilip3CM+ngPlzmPImR2ObchErhiPOfKhrtuR02+im+ozZ5wCtY7WCD893leoeu1ownKbUEEYhAwUXyeeYqNOKpXVHH9XRNNTMOafTCl27UFhgz0curcaWuk84fl6jOsnY0KW07No4uUyp4z3zfW14/iv5D1gvUeNN7wcXZKeUaGuo0pUWTo6zPwbgaGPHe5NKNeFwhH0UL3nduaLlBsS/DYlzhgnnLqVPFE1h6yL79tO1YAVTyhNnkfw7HPwrPgaOmzeUGiN54Sbw2EALHWTmpVzHXP3zxB6omd+GAt2Pf+Kk9Ol63eZSCf1AoIKr0GU/d5f51e3Ozo8KIg2HS3N67R9wcUZI/0jZM5cb89+W1lYg1UdcWZQfsUxJzQgPFWq1SzPdN56ethKTJWghb29ygMc1VrEm5c=
