language: python
python:
  - "3.6"
install:
  - pip install -r requirements/base.txt
  - pip install coveralls
script:
  - coverage run --source='.' manage.py test gambit
after_success:
  - coveralls
